name: Cypress Tests

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-24.04
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout do projeto
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      # 🔥 AGORA GERA JSON DE VERDADE
      - name: Rodar Cypress
        run: npx cypress run --spec "cypress/e2e/Filtros.cy.js" --reporter mochawesome --reporter-options "reportDir=cypress-report,reportFilename=report,overwrite=true,json=true,html=false"

      - name: Instalar jq
        run: sudo apt-get install -y jq

      # 🔥 AGORA FUNCIONA
      - name: Gerar resumo do teste
        if: always()
        run: |
          echo "## Cypress Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          PASSED=$(jq '.stats.passes' cypress-report/report.json)
          FAILED=$(jq '.stats.failures' cypress-report/report.json)
          DURATION=$(jq '.stats.duration' cypress-report/report.json)

          echo "| Status | Valor |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| 🟢 Passed | $PASSED |" >> $GITHUB_STEP_SUMMARY
          echo "| 🔴 Failed | $FAILED |" >> $GITHUB_STEP_SUMMARY
          echo "| ⏱ Duration | $DURATION ms |" >> $GITHUB_STEP_SUMMARY